import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { MyContextProvider } from "@/state/context";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SCO 311 ASSIGMENT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyContextProvider>   
       <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="mt-[0px]">
          {children}
        </div>
      </body>
    </html>
    </MyContextProvider>

  );
}


// npx tailwindcss -i ./app/globals.css -o ./app/output.css --watch