import Landing from "@/components/Landing";
import Image from "next/image";

export const metadata = {
  title: "SCO 311 ASSIGMENT",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main>
      <Landing />
    </main>
  );
}
